version: '3'
services:
  http1:
    image: "winnovature/unitia:production" 
    user: "1000:1000"
    ports:
      - "8001:8080"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
    depends_on:
      - "router1"
    environment:
      - module=http
      - TZ=Asia/Kolkata  
  http2:
    image: "winnovature/unitia:production"
    user: "2001:1000"
    ports:
      - "8002:8080"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
    depends_on:
      - "router1"
    environment:
      - module=http
      - TZ=Asia/Kolkata
  smpp:
    image: "winnovature/unitia:production"
    ports:
      - "2775:8080"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
    depends_on:
      - "router1"
    environment:
      - module=smpp
      - TZ=Asia/Kolkata
  submission:
    image: "winnovature/unitia:production"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
    depends_on:
      - "delivery"
    environment:
      - module=submission
      - TZ=Asia/Kolkata
  delivery:
    image: "winnovature/unitia:production"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
    depends_on:
      - "scheduledb"
    environment:
      - module=delivery
      - TZ=Asia/Kolkata
  dnsql:
    image: "winnovature/unitia:production"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
    depends_on:
      - "kannel1"
    environment:
      - module=dnsql
      - TZ=Asia/Kolkata
  demo:
    image: "winnovature/unitia:production"
    ports:
       - "4001:8080"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
    environment:
      - module=demo
      - TZ=Asia/Kolkata
  scheduledb:
    image: "winnovature/unitia:production"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
    depends_on:
      - "dnpostdb" 
    environment:
      - module=scheduledb
      - TZ=Asia/Kolkata
  dnpostdb:
    image: "winnovature/unitia:production"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
    depends_on:
      - "dbtoredis"
    environment:
      - module=dnpostdb
      - TZ=Asia/Kolkata
  dbtoredis:
    image: "winnovature/unitia:production"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
    depends_on:
      - "tablereader"
    environment:
      - module=dbtoredis
      - TZ=Asia/Kolkata
  tablereader:
    image: "winnovature/unitia:production"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
    depends_on:
      - "dnhttppost"
    environment:
      - module=tablereader
      - TZ=Asia/Kolkata
  dnhttppost:
    image: "winnovature/unitia:production"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
    depends_on:
      - "redisqueue1"
      - "unitiadb"
    environment:
      - module=dnhttppost
      - TZ=Asia/Kolkata
  router1:
    image: "winnovature/unitia:production"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
    depends_on:
      - "redisqueue1"
      - "kannel1"
    environment:
      - module=router
      - redis=redisqueue1 
      - TZ=Asia/Kolkata
  redisqueue1:
    image: "winnovature/redis:production"
    ports:
      - "2001:6379" 
    volumes:
      - /home/unitia/production/redisqueue1/data/:/data
  kannel1:
    image: "kannel"
    ports:
      - "13013:13013" # smsbox
      - "13000:13000" # kannel admin
    depends_on:
      - kannelconfig
    volumes:
      - "/home/unitia/production/spool/kannel1:/var/spool/kannel"
      - "/logs/kannel1:/var/log/kannel"
      - "/etc/hosts:/etc/hosts"
      - "/home/unitia/production/kannel1:/etc/kannel"
      - "./opensmppbox.conf:/etc/kannel/opensmppbox.conf"
    environment:
      - "LANG=en_US.UTF-8"
      - "LC_ALL=en_US.UTF-8"
      - "TZ=Asia/Kolkata"
  unitiadb:
    image: "winnovature/mariadb:production"
    ports:
      -  "3306:3306"
    volumes:
      - "/home/unitia/production/mysql:/var/lib/mysql"
      - "/home/unitia/production/mysql/my.cnf:/etc/mysql/my.cnf"
    environment:
      - MYSQL_ROOT_PASSWORD=kannel 
      - TZ=Asia/Kolkata
    networks:
      default:
        aliases:
          - "unitia.mysql.ip" 
  kannel1db:
    image: "winnovature/mariadb:production"
    ports:
      -  "3307:3306"
    volumes:
      - "/home/unitia/production/kannel1db:/var/lib/mysql"
      - "/home/unitia/production/kannel1db/my.cnf:/etc/mysql/my.cnf"
    environment:
      - MYSQL_ROOT_PASSWORD=kannel
      - TZ=Asia/Kolkata
  kannelconfig:
    image: "winnovature/unitia:production"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
      - /logs:/logs
    depends_on:
      - "unitiadb"
      - "kannel1db"
    environment:
      - module=kannelconfig
      - TZ=Asia/Kolkata
  logs:
    image: "winnovature/unitia:production"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
      - /logs:/logs
    environment:
      - module=logs
      - TZ=Asia/Kolkata
  http:
    image: "winnovature/http-haproxy:production"
    ports:
      - "9090:8080"
    depends_on:
      - "http1"
      - "http2"
