version: '3'
services:
  router:
    image: "winnovature/unitia:production"
    volumes:
      - /logs:/logs
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
    environment:
      - module=router
      - redis=rq2
      - TZ=Asia/Kolkata

