version: '3'
services:
  simulator1:
    image: "winnovature/unitia:production"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
      - /logs:/logs
    environment:
      - module=simulator
      - TZ=Asia/Kolkata
  kannel1:
    image: "winnovature/kannel:sqldn"
    ports:
      - "13112:13013" # smsbox
      - "13100:13000" # kannel admin
    depends_on:
      - kannelconfig
      - kannel1db
    volumes:
      - "/home/unitia/production/spool/kannel1:/var/spool/kannel"
      - "/logs/kannel1:/var/log/kannel"
      - "/etc/hosts:/etc/hosts"
      - "/home/unitia/production/kannel1:/etc/kannel"
      - "./opensmppbox.conf:/etc/kannel/opensmppbox.conf"
    environment:
      - "LANG=en_US.UTF-8"
      - "LC_ALL=en_US.UTF-8"
  kannel1db:
    image: "winnovature/mariadb:production"
    ports:
      -  "3316:3306"
    volumes:
      - "/home/unitia/production/kannel1db:/var/lib/mysql"
      - "/home/unitia/production/kannel1db/my.cnf:/etc/mysql/my.cnf"
    environment:
      - MYSQL_ROOT_PASSWORD=kannel
      - TZ=Asia/Kolkata
  kannelconfig:
    image: "winnovature/unitia:production"
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/unitia/:/unitia
      - /logs:/logs
    depends_on:
      - "kannel1db"
    environment:
      - module=kannelconfig
      - TZ=Asia/Kolkata

